channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  # For the template:
  - python>=3.10
  - setuptools>=61.0.0
  - setuptools_scm
  - wheel
  - pip
  - click
  - flake8
  - python-dotenv>=0.5.1
  - pip:
      - -e . # Our local package
      - vizta

  # Data Science Packages
  - numpy
  - pandas
  - polars
  - matplotlib
  - seaborn
  - scikit-learn
  - ipykernel
  - awswrangler
